import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "@/components/banner/banner";
import NavBar from "@/components/navbar/navbar";
import SectionCards from "@/components/card/section-cards";
import { getPopularVideos, getVideos, getWatchItAgainVideos } from "@/lib/videos";
import { video } from "@/types";
import { InferGetServerSidePropsType,GetServerSideProps } from "next";
import { verifyToken } from "@/lib/utils";

export const getServerSideProps = (async ({req}) => {
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();
  const token = req?.cookies?.token;
  const userId = verifyToken(token as string);
     
  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const watchedVideos = await getWatchItAgainVideos((token as string),userId);


  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
      watchedVideos
    },
  };
}) satisfies GetServerSideProps<
  { disneyVideos: video[], productivityVideos: video[], 
    travelVideos: video[],popularVideos: video[],watchedVideos: video[] }>;
export default function Home(
  {disneyVideos, productivityVideos, travelVideos,popularVideos,watchedVideos}: 
  InferGetServerSidePropsType<typeof getServerSideProps>
) {
  return (
    <div className={styles.container}>
      <Head>
        <title >Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <NavBar/>
        <Banner  videoId="4zH5iYM4wJo" title ='Unlimited movies, TV shows, and more' 
          subTitle="Starts at EGP 100. Cancel anytime. Ready to watch? " imageUrl="/static/background.webp" />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" size="large" videos={disneyVideos}/>
          <SectionCards title="Watch it again" size={"small"} videos={watchedVideos}/>
          <SectionCards title="Travel" size="small" videos={travelVideos}/>
          <SectionCards title="Productivity" size={"medium"} videos={productivityVideos}/>
          <SectionCards title="Popular" size={"small"} videos={popularVideos}/>
        </div>
      </div>
    </div>
  );
}
